# docker compose version
version: "3.8"

services:
  mysql:
    ports:
      - "3307:3306"
    # restart: always
    image: mysql:5.7
    volumes:
      # named volume (path obtained from MySQL Docker Hub)
      - data:/var/lib/mysql
      # init.sql file
      - ./server:/docker-entrypoint-initdb.d
    container_name: mysql_container
    env_file:
      - ./server/env/mysql.env
    # healthcheck tells Docker if the state of the container is normal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # checks every 20 seconds
      timeout: 20s
      retries: 10

  backend:
    restart: always
    # building the image
    build: ./server
    ports:
      - "3002:3002"
    volumes:
      - ./server:/app
      - /app/node_modules
    container_name: backend_container
    env_file:
      - ./server/env/backend.env
    # depends_on sets the order in which services must start and stop.
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql

  frontend:
    restart: always
    build: ./client
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      # bind mount
      - ./client/src:/app/src
    # interactive mode (-it)
    stdin_open: true
    tty: true
    depends_on:
      - backend

# syntax for named volumes
volumes:
  data:
